version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mixanemca/regru-go
